apiVersion: v1
kind: Service 
metadata:
  name: billing-app-back-service
  labels:
    app: billing-app-back
spec:
  type: NodePort
  ports:
    - name: billing-app-back
      port: 7080
      nodePort: 30780
  selector:
    app: billing-app-back